### ISSUE TITLE
Paragraph are not joined by spaces

### ISSUE THREAD

**Issue by JuanCaicedo** [frontarm/mdx-util#24]
Hi there!

My impression with markdown is that you can split a paragraph of text into many lines and they will be joined together by spaces:
```markdown
# header
a
b

c
d
```
should become 
```html
<h1>Header</h1>
<p>a b</p>
<p>c d</p>
```
However, I think mdxc instead returns this (no spaces)
```html
<h1>Header</h1>
<p>ab</p>
<p>cd</p>
```
Not sure if that's coming from here or from markdown-it, but I'm willing to help identify/fix 😀

**Comment by jamesknelson** [comment]
I've managed to reproduce this, and it is definitely a problem. I guess I've never really used newline mid paragraph so I hadn't noticed it.

The problem is that MDX currently treats each text line as a string child of a React element, but React doesn't put any spaces between these. I'm going to try adding a newline character at the end of every text line and see how it goes.
