### ISSUE TITLE
Access to the `div` element

### ISSUE THREAD

**Issue by helfi92** [frontarm/mdx-util#36]
I have a markdown file with the following content:

```
# Foo

## Schema

<div data-render-schema='http://schemas.taskcluster.net/queue/v1/create-task-request.json'></div>
```

I am trying to find a way to have access to `<div>` elements in markdowns and having them replaced with a React element.

I tried the following but the `schemaViewer` function is not being triggered:

```jsx
const components= {
  div: this.schemaViewer,
};

// ...

schemaViewer = ({ props, children }) => {
  const url = children.props['data-render-schema'];

  if (url) {
    return <SchemaTable url={url} />;
  }

  return children;
};

// ...

<MarkdownDocument components={components} /> 
```

Do you know of a way I can have access to the element without modifying the original markdown file? Any help is appreciated. Thanks!

**Comment by jamesknelson** [comment]
It look correct to me. Could you put together a reproduction with https://frontarm.com/demoboard/ so I can take a look?

**Comment by helfi92** [comment]
https://frontarm.com/demoboard/?id=7b9f3bc1-43b6-4687-bfef-5aaab0f9885a

**Comment by jamesknelson** [comment]
Just realized that I messed up by saying it looks like it should work. After taking a look at the example, the issue here is that `components` only lets you configure components that are automatically generated by MDX.

Since the link in the above example uses `[]()` syntax, MDX generates a `<a>` component, and that can be configured.

However, the `<div>` is manually added in as JSX, so it can't be replaced. You'd find that if you manually wrote `<a href="https://google.ca">Google</a>`, then the link wouldn't be replaced either.

**Comment by helfi92** [comment]
Thanks for looking into it @jamesknelson. What you say makes sense. In that case, do you have any recommendations on how I would be able to get a hold of that `<div>` element. I specifically want a way to access the `data-render-schema` attribute of the element. Many thanks.

**Comment by jamesknelson** [comment]
Replacing a div in some JSX with another can be done by looking in the elements props and using cloneElement, but I think it’s be easier to just import the SchemaTable element in the MDX file and use it directly.

**Comment by helfi92** [comment]
Sounds good. Many thanks @jamesknelson!
